In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('..\Data\customer_churn_dataset-training-master.csv')

In [39]:
df = df.dropna()

In [40]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [41]:
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [42]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [43]:
cat = [col for col in df.columns if df[col].dtype == 'O']

In [44]:
cat

['Gender', 'Subscription Type', 'Contract Length']

In [46]:
df.head()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Female,Gender_Male
0,2.0,30.0,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0,1,0
1,3.0,65.0,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0,1,0
2,4.0,55.0,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0,1,0
3,5.0,58.0,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0,0,1
4,6.0,23.0,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0,0,1

In [47]:
df['Subscription Type'].value_counts()

Subscription Type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: int64

In [48]:
df['Subscription Type'] = df['Subscription Type'].map({'Basic' : 0 , 'Standard' :1 ,'Premium':2})

In [49]:
df.head()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Female,Gender_Male
0,2.0,30.0,39.0,14.0,5.0,18.0,1,Annual,932.0,17.0,1.0,1,0
1,3.0,65.0,49.0,1.0,10.0,8.0,0,Monthly,557.0,6.0,1.0,1,0
2,4.0,55.0,14.0,4.0,6.0,18.0,0,Quarterly,185.0,3.0,1.0,1,0
3,5.0,58.0,38.0,21.0,7.0,7.0,1,Monthly,396.0,29.0,1.0,0,1
4,6.0,23.0,32.0,20.0,5.0,8.0,0,Monthly,617.0,20.0,1.0,0,1

In [50]:
df['Contract Length'].value_counts()

Contract Length
Annual       177198
Quarterly    176530
Monthly       87104
Name: count, dtype: int64

In [51]:
df['Contract Length'] = df['Contract Length'].map({'Monthly' :0 , 'Quarterly' :1 , 'Annual':2 })

In [52]:
df.head()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Female,Gender_Male
0,2.0,30.0,39.0,14.0,5.0,18.0,1,2,932.0,17.0,1.0,1,0
1,3.0,65.0,49.0,1.0,10.0,8.0,0,0,557.0,6.0,1.0,1,0
2,4.0,55.0,14.0,4.0,6.0,18.0,0,1,185.0,3.0,1.0,1,0
3,5.0,58.0,38.0,21.0,7.0,7.0,1,0,396.0,29.0,1.0,0,1
4,6.0,23.0,32.0,20.0,5.0,8.0,0,0,617.0,20.0,1.0,0,1